### ISSUE TITLE
Come up with 3 potential issues to vote on

### ISSUE THREAD

**Issue by gmarks-ut** [gmarks-ut/QMB210-FA24#1]

**Comment by kaylynott** [comment]
Team 2

Topics: Housing, Dining, School Spirit

**Comment by nicolefdz** [comment]
**Team 1**

Main topic ideas:
**-Housing** 
 	-Convenience 
	-Move-In
**-Dinning Hall**
	-Timing
	-Quality
**-Campus Involvement** 
	-School Spirit
	-Sports

**Comment by anacrisostomo09** [comment]
QMB 210-5

**Team 1:** 

- School Spirit
- Dining Hall
- Class Schedule 
- On Campus Housing

**Comment by gmarks-ut** [comment]
Good job!

**Comment by gmarks-ut** [comment]
Awesome, good job!

**Comment by gmarks-ut** [comment]
Good job!

**Comment by morgan-wimberly** [comment]
Team 2
1. Campus Resources (how often speech center, career services, etc.) is being used
2.  Wifi (working in specific buildings, etc.)
3. Dining options on campus

**Comment by George2195** [comment]
School Spirit, On Campus housing, UT Football Team

**Comment by colemane22** [comment]
Team 1 topic Ideas:
On-Campus Dining
Greek Life
Sports/Campus Involvement

**Comment by Evan-22** [comment]
Team 3 
Favorite place to go out 

Favorite restaurant 

Housing on vs off campus

**Comment by gmarks-ut** [comment]
Good job!

**Comment by gmarks-ut** [comment]
Good job!

**Comment by gmarks-ut** [comment]
Good job!

**Comment by gmarks-ut** [comment]
Good job!

**Comment by Justin-Tomasina** [comment]
QMB 210-5
Team 3, 3 Potential Topic Issues
1. Attendance at sports games/school spirit
2. Intramural sport participation
3. New Grubhub system for Spartan Club dining

**Comment by gmarks-ut** [comment]
Gret job!
