### ISSUE TITLE
Pick a junior Scrum Master to do Qualtrics Survey and 2 people to help

### ISSUE THREAD

**Issue by gmarks-ut** [gmarks-ut/QMB210-FA24#2]

**Comment by kaylynott** [comment]
Team 

Junior Masters: Nica & Daan
Helpers: Peyton & Khalid

**Comment by anacrisostomo09** [comment]
Junior Scrum Master (Qualtrics): Gabriel Ariza 
Helper 1: Maria Buttaci 
Helper 2: Rachel Gregg
Junior Scrum Master: TBD

**Comment by gmarks-ut** [comment]
Good job!

**Comment by gmarks-ut** [comment]
Good job!

**Comment by morgan-wimberly** [comment]
Team 2
Junior Scrum for Qualtrics: Kaitlyn Arena

**Comment by Evan-22** [comment]
Team 3
Junior Scrum Masters: Katya (qualtics) and Gabe (Excel)

**Comment by gmarks-ut** [comment]
Good job!

**Comment by gmarks-ut** [comment]
Good job!

**Comment by Justin-Tomasina** [comment]
QMB 210-5
Team 3 Junior Scrum Masters
Qualtrics: Ronan Flanigan
Excel: Shreeya Saha

**Comment by gmarks-ut** [comment]
Great job!

**Comment by colemane22** [comment]
QMB 210-7
Team 1 Junior Scrum Masters:
Kevin Prime (Qualtrics) and Conley Stone (Excel)
Helpers: Josh Sentell, TBD

**Comment by nicolefdz** [comment]
Junior Scrum Master Qualtrics: Nicole Fernandez
Helper 1: Kristina Guatto
Helper 2: Victoria Logan

Junior Scrum Master Excel: Elizabeth Simon

**Comment by andrewa131930** [comment]
QMB 210-5
Junior scrum master: Kayla
Helper 1: charlie
Helper 2 Devon

**Comment by George2195** [comment]
QMB 210-7 group 3 

Junior scrum Master - Daniel sohn 
Helper 1 - Lauren Jones 
Helper 2 - Jake Labadie

**Comment by gmarks-ut** [comment]
Good job!

**Comment by gmarks-ut** [comment]
Great job!
