### ISSUE TITLE
Decide a time to do first zoom Scrum Call this week

### ISSUE THREAD

**Issue by gmarks-ut** [gmarks-ut/QMB210-FA24#3]

**Comment by kaylynott** [comment]
Team 

Sunday @ 8:30pm

**Comment by anacrisostomo09** [comment]
QMB 210-5
**Team 1**
Sunday 8:00 pm

**Comment by andrewa131930** [comment]
QMB210-5
**Team 2**

Sunday @ 2:00PM

**Comment by gmarks-ut** [comment]
Awesome, good job!

**Comment by gmarks-ut** [comment]
Awesome, good job!

**Comment by nicolefdz** [comment]
Team 1

August, 30 at 4:00 pm

Zoom link: 
https://utampa.zoom.us/j/97897334084?pwd=v9iwRlFBDyHpYMvdiBdlBZo9HjAQPN.1

Meeting ID: 978 9733 4084
Passcode: 772676

**Comment by gmarks-ut** [comment]
Great job!

**Comment by colemane22** [comment]
QMB 210-7
Team 1 Meeting Time
Sunday @ 9 p.m.

**Comment by morgan-wimberly** [comment]
Team 2
4pm on Thursday, August 29th

**Comment by Evan-22** [comment]
Team 3 
Sundays at 7pm weekly meetings

**Comment by gmarks-ut** [comment]
Good job!

**Comment by gmarks-ut** [comment]
Good job!

**Comment by gmarks-ut** [comment]
Good job!

**Comment by Justin-Tomasina** [comment]
QMB 210-5
Team 3 Meeting Time
Friday 8/30 @3:30pm

**Comment by gmarks-ut** [comment]
Great job!

**Comment by George2195** [comment]
George Group 

10 Pm monday
