### ISSUE TITLE
In Scrum Call Decide on topic

### ISSUE THREAD

**Issue by gmarks-ut** [gmarks-ut/QMB210-FA24#4]

**Comment by morgan-wimberly** [comment]
Team 2/QMB 210-7
During our call, we decided that we will be doing how often various campus resources (including but not limited to career services and speech center) are utilized by students.

**Comment by Justin-Tomasina** [comment]
QMB 210-5 
Team 3
Topic: New Grub Hub system for on campus dining, mainly in spartan club. Addressing if the system is better or worse than previous and the reasons as to why.

**Comment by gmarks-ut** [comment]
That sounds great, none of my students have ever done that before.  Very original!

**Comment by kaylynott** [comment]
Our group decided on dining as our topic, and anything overall regarding to the finding halls on campus.

**Comment by anacrisostomo09** [comment]
On Campus Housing

**Comment by nicolefdz** [comment]
Team 1 
Student Motivations for Choosing Greek Life vs. Academic Clubs

**Comment by Evan-22** [comment]
Team 3 QMB210-2

In our Zoom meeting today we decided to do our project on what students choose to do over the weekends. Whether they attend events/activities on or off campus. We want to see what a typical weekend is like for a UT student and see if there are any patterns in what they choose to do.

**Comment by George2195** [comment]
George Bailey's Group Team 3 2pm -  Football Team

**Comment by colemane22** [comment]
QMB 210-7
team 1 Topic:
In our zoom call we decided that our topic was going to be sports and on-campus involvement. Our hopes with this topic is to find and analyze the motivations that students have to join different clubs. We will also be looking at what clubs perform the best in terms of how many kids sign up/join.

**Comment by andrewa131930** [comment]
QMB 210-5

Team 2 topic: in our zoom call we have decided our topic will be Grand center satisfaction specifically with dining options as they added a second starbucks but not other dining options in such a large building.

**Comment by gmarks-ut** [comment]
Great job!

**Comment by gmarks-ut** [comment]
Great job
